[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "index.html", "input.css"]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i input.css -o style/output.css --minify"]
